carrier web collection
fulfillmenttools/fulfillmenttools-api-reference pull request #150
Opened 2020-10-23 04:59 UTC by adnaniroshanak

2020-10-23 05:23 UTC, timdauer commented on internal/web_backoffice-v1-carriers.json
> +            "isEnabled": {
@Rebstorm @evilass @simwoe @adnaniroshanak Are we sure that the flag "isEnabled" is enough for us? I could think of situations where a status field might come in handy ("CREATED", "AUTHORIZING", "AUTHORIZED", "AUTH_PROBLEM", "DISABLED", etc.)

But: It is your choice of course!

2020-10-23 09:20 UTC, Rebstorm commented on internal/web_backoffice-v1-carriers.json
> +            "isEnabled": {
Right now we only have isEnabled: boolean as a flag because we either disable/show the element depending on this option. My guess is that we would have another field called 'status' or 'progress' for what you're describing.

2020-10-25 22:31 UTC, evilass requested changes

2020-10-25 22:31 UTC, evilass commented on internal/web_backoffice-v1-carriers.json
> +              "type": "string"
Shouldn't that be a boolean?

2020-10-26 10:17 UTC, closed without merging